goravel/fiber

fiber.go, fiber_group.go, utils.go
=> Fix middlewares

README.md, cors_test.go, facades/fiber.go, go.mod, go.sum, group_test.go, response.go, route.go, route_test.go, service_provider.go, view.go, view_test.go
=> feat: Add template feature

context.go, context_request.go, context_request_test.go, context_response.go, context_response_test.go, cors_test.go, go.mod, go.sum, group_test.go, response.go, route.go, route_test.go, utils.go, view.go, view_test.go
=> feat: [#243] Optimize the return of controller

.github/workflows/codecov.yml, context_response_test.go, cors_test.go, group_test.go, route.go
Closes # 
目前 Fiber 在 panic 的时候不会打印错误堆栈跟踪信息，此 PR 为开发环境下的 Fiber 添加了堆栈打印特性。
本地测试此 PR 和 Gin Bug 级兼容，在 Windows 系统下使用`air`运行均无法看到打印输出，直接`go run .`运行则没有问题，不知道什么原因。
=> feat: add debug print

context_request.go, context_request_test.go
=> feat: [#294] Validator cant check the param of url

group.go, group_test.go, response.go, route.go
Closes goravel/goravel#299
Closes goravel/goravel#300
Fix File methods not work.
=> fix: file methods and GlobalMiddleware method

.goreleaser.yaml, context_request.go, group.go, group_test.go, route.go
=> fix: fallback the logic of GlobalMiddleware

.goreleaser.yaml, context_request.go, group.go, group_test.go, route.go
* fix: fallback the logic of GlobalMiddleware
* chore: remove unnecessary file
Closes #
=> fix: fallback the logic of GlobalMiddleware (#42)

README.md
=> docs: fix lint

context_request.go
=> feat: remove unnecessary mutex

route.go
Closes # 
移除自动为证书路径加 `.` ，支持使用绝对路径配置证书。
=> feat: remove path limit

context_request.go, context_response.go
=> feat: performance optimize

context_request.go, context_request_test.go
Closes https://github.com/goravel/goravel/issues/375
=> fix: [#375] [Bug] using fiber, unable to handle files alongside other data with multipart formdata

context_request.go, context_request_test.go
=> merge: v1.1.14

context_request.go, context_response.go
Made `Writer` support `Hijack`, code is copy from fasthttp.
=> feat: optimize writer

go.mod, go.sum
=> upgrade: 1.14.3

go.mod, go.sum, route.go, route_test.go
=> feat: Optmize Shutdown

go.mod, go.sum
=> upgrade: v1.2.4

context_request.go, context_request_test.go
Closes https://github.com/goravel/goravel/issues/528
@coderabbitai summary
=> fix: [#528] GraphQL request causing errors from request body parsing

middleware_timeout.go, middleware_timeout_test.go, route.go
=> chore: optimize recover logic

go.mod, go.sum
=> upgrade: framework v1.15.1

README.md, context_request_test.go, context_response_test.go, group_test.go, middleware_cors_test.go, middleware_timeout_test.go, route.go, route_test.go, view_test.go
Closes https://github.com/goravel/goravel/issues/628
=> feat: add immutable option

README.md, route.go, route_test.go, view_test.go
Closes https://github.com/goravel/goravel/issues/
=> chore: improve path concatenation for better readability

context_request.go, context_request_test.go, go.mod, go.sum
Closes https://github.com/goravel/goravel/issues/376
=> feat: [#376] ctx.Request() supports get multiple files directly

context_request.go, context_request_test.go
Closes https://github.com/goravel/goravel/issues/659
=> fix: [#659] http fiber驱动获取x-www-form-urlencoded数组错误

group_test.go, route_test.go
Closes https://github.com/goravel/goravel/issues/287
=> chore: [#287] optimize tests
